<div id="indexpage">
    <div class="motto">A website for everyone</div>
    <p class="welcometext">SanjaySites helps you launch your website easily and cheaply. <a href="/index/signup">Sign up</a> for an account now, its free.</p>
    <p class="welcometext">Manage your website or your web profile with our site builder tool. You could change the whole dynamic content of your website anytime, save the changes, and view the results. All without spending a penny on a web designer or a web developer.  </p>
    <p class="welcometext">Its easy to build, change and publish, and ofcourse its free!</p>
    <p class="welcometext">So get started right <a href="/index/signup">here</a>.</p>
</div>