<html>
    <head>
        <title>SanjaySites - A website for everyone</title>
        <link rel="stylesheet" type="text/css" href="/css/general.css">
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js"></script>
        
        <script>
        $(function(){
			//alert('Sanjay');
        });
        </script>
    </head>
<body>

<!-- The main container starts here -->
<div id="container">

    
<!-- Header -->
<div id="header">
<!-- <h2>SanjaySites</h2> -->
<a href="/"><img alt="sanjaysites - a website for everyone" src="/images/mainlogo.png" border="0" ></a>
</div>
<!-- Header -->

<div id="seperator">&nbsp;</div>

<!-- Left -->
<div id="left">
    <?php echo $this->layout()->content; ?>
</div>
<!-- Left -->



<!-- Footer -->
<div id="footer">
    <div id="copyright">Venture by webnanos.com</div>
</div>
<!-- Footer -->

</div>
<!-- The main container ends here -->

</body>
</html>